#!/bin/sh
#
# Script to run after doing a git pull
#
# Note that we might need to do:
# git submodule update --init --recursive
# or
# git submodule update --recursive
#
# Emacs is taken as /Applications/Emacs.app/Contents/MacOS/Emacs if it
# exists (a Mac platform), otherwise, we just use emacs.
if [[ -x /Applications/Emacs.app/Contents/MacOS/Emacs ]] ; then
    EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs
else
    EMACS=emacs
fi

# First, make all the .elc files:

if ! ${EMACS} -batch -l batch-commands.el -f batch-byte-recompile-directory-all . ; then
    echo batch-byte-recompile failed
    exit 1
fi

# Now, update the myloaddefs.el file:

find . -type f -name '*.el' -print | \
    egrep -v '/\.git' | \
    egrep -v /nxhtml/ | \
    xargs egrep -l '# *autoload' | \
    xargs ${EMACS} \
        -batch \
        -l batch-commands.el \
        -f batch-update-my-autoloads

# We don't want myloaddefs.el compiled because it confuses me.

rm -f pedz/myloadsdefs.elc nxhtml-834/main/util/ourcomments-util.elc
( cd magit && make )
find . -name '*.elc' -print | xargs -I files mv files elc
