# Makefile for creating HTML documentation for CEDET project.
# 

DEST=/Users/pedz/src/emacs/cedet/htdocs/info
DIR=$(shell pwd)
VPATH= eieio speedbar semantic/doc ede cogre

all: $(DEST)/eieio.html \
     $(DEST)/speedbar.html \
     $(DEST)/semantic.html \
     $(DEST)/ede.html \
     $(DEST)/cogre.html


$(DEST)/%.html: %.texi
	cd $(DEST) ; \
	makeinfo --html -I $(dir $(DIR)/$<) -o $@ $(DIR)/$<

#end
